### ISSUE TITLE
Web link 

### ISSUE THREAD

**Issue by robinsone** [jo-sm/highlights#1]
Hey jo-sm, 

I just noticed that your link is incorrect. I believe you changed your username and so your gh-pages branch isn't producing a website.

**Comment by jo-sm** [comment]
Wow -- I didn't notice this message for 9 months and only saw it because I was cleaning house in my repositories... Sorry! I updated the URL in my description and also fixed the Ractive library URL so that the page loads correctly. Here's the updated link: https://jo-sm.github.io/highlights/
